=== torvics/SchemaDTD/src/Cancionxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="canciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name = "cancion" maxOccurs="unbounded" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name = "titulo" type="xs:string"/>

              <xs:element name = "compositores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name = "compositor">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name = "nombre" type="xs:string"/>
                          <xs:element name = "apellidos" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name = "productores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name = "productor">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name = "nombre" type="xs:string"/>
                          <xs:element name = "apellidos" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name = "sello" type="xs:string"/>

              <xs:element name = "artista" type="xs:string"/>

            </xs:sequence>
            <xs:attribute name="duracion" type="xs:string"/>
            <xs:attribute name="aÃ±o" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== torvics/SchemaDTD/src/Cancionxsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<canciones xsi:noNamespaceSchemaLocation = "Cancionxsd.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema">

    <!-- cancion 1 -->
    <cancion duracion = "4:47" año = "2008">

        <titulo> Give it 2 me </titulo>
        <compositores>
            <compositor>
                <nombres> Pharrell </nombres>
                <apellidos> Williams </apellidos>
            </compositor>
        </compositores>

        <productores>
            <productor>
                <nombres> Pharrell </nombres>
                <apellidos> Williams </apellidos>
            </productor>
        </productores>

        <sello> Warner Bros. Records </sello>

        <artista> Maddona </artista>

    </cancion>

    <!-- cancion 2 -->
    <cancion duracion = "3:38" año = "2014">

        <titulo> Shake it off </titulo>
        <compositores>
            <compositor>
                <nombres> Taylor </nombres>
                <apellidos> Swift </apellidos>
            </compositor>
            <compositor>
                <nombres> Max </nombres>
                <apellidos> Martin </apellidos>
            </compositor>
        </compositores>

        <productores>
            <productor>
                <nombres> Max </nombres>
                <apellidos> Martin </apellidos>
            </productor>
        </productores>

        <sello> Big Machine Records </sello>

        <artista> Taylor Swift </artista>

        <!-- cancion 3-->
    </cancion>

    <cancion duracion = "10:13" año = "2021">

        <titulo> All too well (10 minutes version) (Taylor's Version) (From the Vault) </titulo>
        <compositores>
            <compositor>
                <nombres> Taylor </nombres>
                <apellidos> Swift </apellidos>
            </compositor>
        </compositores>

        <productores>
            <productor>
                <nombres> Taylor </nombres>
                <apellidos> Swift </apellidos>
            </productor>
        </productores>

        <sello> Universal Music </sello>

        <artista> Taylor Swift </artista>

    </cancion>

</canciones>
